const FORM_ITEM_TYPE = {
    INPUT:'INPUT',
    INPUT_NUMBER:'INPUT_NUMBER',
    MULTIPLE_SELECT: 'MULTIPLE_SELECT',
    SELECT: 'SELECT',
    NUMBER: 'NUMBER',
    TEXT: 'TEXT',
    LONG_TEXT: 'LONG_TEXT',//文本域
    DATE: 'DATE',
    IMAGE: 'IMAGE',
    SWITCH: 'SWITCH',
    SLIDER: 'SLIDER',//滑动选择器
    CASCADER: 'CASCADER',
    RANGE_PICKER:'RANGE_PICKER',
    RANGE_PICKER1:'RANGE_PICKER1',
    EDIT: 'EDIT'// 富文本

};

export default FORM_ITEM_TYPE;
